### ISSUE TITLE
Bug Major: Log-in Input Leads to Error

### ISSUE THREAD

**Issue by sloaneshea** [info442-su23/i-team#56]
1. Bug Major
2. When I clicked submit on the log-in page, an error popped up Firebase: Error (auth/user-not-found).
3. Google Chrome Version 115.0.5790.114 (Official Build) (x86_64)
4. Press home, log in, type in input, press enter
5. Home Screen
6. Error pop-up
7. 
<img width="675" alt="Screen Shot 2023-08-08 at 8 27 30 PM" src="https://github.com/info442-su23/i-team/assets/77075019/7855fc5a-c52a-4705-8f62-a6adedcecf37">

**Comment by asingh0725** [comment]
The major bug reported is invalid. We couldn't reproduce the result. Users need to register their UW accounts before trying to login into the application.
