### ISSUE TITLE
Bug Minor - Image posts and numbered items overlap 

### ISSUE THREAD

**Issue by phyllisUW** [info442-su23/i-team#59]
Minor bug
Number that describes amount of images in a post on the top right is covered by the image
Encountered on Microsoft Edge (Version 115.0.1901.188)
Change the way the text element of "# of #" in image is positioned relative to images
Expected Result: Image and the text "1 of 1" next to the image, to the top right
Actual Result: Image and the text overlap
<img width="822" alt="image" src="https://github.com/info442-su23/i-team/assets/91918592/1f097f8e-3307-4171-a41b-c5388eae6313">

**Comment by asingh0725** [comment]
Thank you for pointing this out! We will fix this in phase 10.
