### ISSUE TITLE
Feature request：Personal post collection

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/i-team#60]
Description of the requested feature: It would be more convenient for user to have a collection.

Why: 
1. After I make a post, there is no place for me to check my post. I do not know how many post I have make.
2. Also, the home page post order is in random, which is hard for me to find my post

Examples: https://www.instagram.com/

**Comment by asingh0725** [comment]
The first issue mentioned is very similar to #57 (creating a unique page for each post). We will fix the second issue in phase 10 by sorting all posts from newest to oldest by default.
