### ISSUE TITLE
Feature request: Progress for add ava

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/i-team#62]
Description of the requested feature: It would be more clear to have a percent progress for avatar adding. 
Why: After I add my avatar, there is no indicator whether I upload it sucessufully, do I just need to wait or choose the img again?
Examples: https://game-recommendation-vic.web.app/add

**Comment by asingh0725** [comment]
Thank you for the suggestion! However, due to other priority tasks for the next sprint, we won't be able to incorporate this.
