### ISSUE TITLE
User profile intrudction

### ISSUE THREAD

**Issue by siyuanji1** [info442-su23/i-team#63]
There should be an introduction explaining the purpose of the user icon. When I clicked on it after logging in, it seemed like I needed to upload something, but I was unsure what. It would be better to provide a page or index detailing what I should upload, to clarify the process.

**Comment by asingh0725** [comment]
Unfortunately, we are not sure whether this is a bug, a feature request, or a combination of both. Parts of this issue are similar to #74.
