### ISSUE TITLE
Bug Major: Profile Button Issue

### ISSUE THREAD

**Issue by wphan-1925132** [info442-su23/i-team#65]
Using Chrome on Windows
When I click on the profile button on the right side of the navigation bar, I expect to see my profile and edit my account or view all my posts in one place. But instead, it directs me to my personal devices folder and makes me open a file? I don't know why this function does or needs that.

![image](https://github.com/info442-su23/i-team/assets/56050048/e396e94e-2d3d-474d-843d-864d3972cab5)

**Comment by asingh0725** [comment]
Thank you for the comment! The image icon is a placeholder and provides users an option to upload their desired user image or stick to the default placeholder image. We plan to make the placeholder and upload button more descriptive in the next sprint.
