### ISSUE TITLE
Add UW branding logo and "Sign in" header on sign-in page(Feature Request)

### ISSUE THREAD

**Issue by bonglrob** [info442-su23/i-team#66]
Rationale: Adding the UW logo branding would legitimize the platform and have students be more confident about signing in with netID
 Having the header also makes it clear
 
![brave_L8q9NEG8hl](https://github.com/info442-su23/i-team/assets/8757841/37fe5715-216f-49ad-a6c7-b9a0d2590be7)

**Comment by asingh0725** [comment]
Thank you for the suggestion! We plan to incorporate the UW log in design on our login page in phase 10.
