### ISSUE TITLE
Feature Request: add a `Start` button on the `About` page.

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/i-team#67]
Summary: It will be nice to have a button at the bottom of the description to take user to the homepage/login page.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: About
Expected Result: Have a button to help navigate
Actual Result: No button

**Comment by asingh0725** [comment]
Thank you for the comment. Since the About page is different from our landing page, we are not sure where to put a 'start' button on the About page.
