### ISSUE TITLE
Profile picture disappearing and has inconsistent sizes (Minor bug)

### ISSUE THREAD

**Issue by FastFusion5** [info442-su23/i-team#68]
I was just pressing the pages on the home page and some of the profile pictures are displayed incorrectly. Also, the profile pictures shown have inconsistent sizes which lead to inconsistent formatting across the entire page. I was expecting that the profile pictures should display correctly and have consistent sizing.
<img width="759" alt="Screenshot 2023-08-09 at 9 45 38 AM" src="https://github.com/info442-su23/i-team/assets/77070825/3f57aa09-b124-40ef-9a16-5e7f24c5e9e6">

<img width="733" alt="Screenshot 2023-08-09 at 9 43 53 AM" src="https://github.com/info442-su23/i-team/assets/77070825/51efbcdb-c894-496e-9b83-391dc9220146">

**Comment by asingh0725** [comment]
Thank you for pointing this out! We can fix the styling issues by having uniformity across image sizes. As for images not displaying, it is an asynchronous loading issue as some of our components fetch from firebase, which is an asynchronous process. We intend to fix these issues in phase 10.
