### ISSUE TITLE
Bug Minor - Login redirects to blank page

### ISSUE THREAD

**Issue by syd-moral** [info442-su23/i-team#69]
Summary: when logging back into created account, takes to blank page with just the header and footer.
Environment: Latest version of Chrome on MacOS
Steps to reproduce: Create account, and then log out. Log in again and close pop-up telling to verify email.
Expected result: takes you to home page
Actual result: blank page
<img width="1440" alt="Screen Shot 2023-08-08 at 6 47 37 PM" src="https://github.com/info442-su23/i-team/assets/97127428/68fc27f0-057f-4d4b-92e2-a89a10021ac4">

**Comment by DongTianjia** [comment]
<img width="1280" alt="Screen Shot 2023-08-09 at 13 26 47" src="https://github.com/info442-su23/i-team/assets/87292522/71b16eb9-58c1-43aa-a70f-b78ff12bc637">

Summary: When logging back into created account, takes to blank page with just the header and footer. Adding on to the info above, the profile button does not render. 

Environment: Latest version of Chrome on MacOS

Steps to reproduce: Create account, and then log out. Log in again and close pop-up telling to verify email.

Expected result: Home page appears with correctly rendered profile button. 

Actual result: blank page with no profile button.

**Comment by asingh0725** [comment]
Thank you for the comment. We tried reproducing the steps but didn't notice any issues mentioned and it was working as expected.
