### ISSUE TITLE
Adding visible borders to each post card (Feature request)

### ISSUE THREAD

**Issue by DongTianjia** [info442-su23/i-team#71]
It would be nice to have clear borders around each post so that it is more clear which line of text and card elements are belong to which post. 

<img width="592" alt="Screen Shot 2023-08-09 at 13 35 01" src="https://github.com/info442-su23/i-team/assets/87292522/a1d4b1cd-49a3-4dde-b92d-27f56d4af897">

**Comment by asingh0725** [comment]
Similar to #70
