### ISSUE TITLE
Pictures are very small on mobile- major

### ISSUE THREAD

**Issue by Ghermo35** [info442-su23/i-team#72]
![F3CB2539-CA7B-428D-836D-F670FB864132](https://github.com/info442-su23/i-team/assets/43656152/bc773fee-3ba6-4203-a00d-1a4984290b66)

**Comment by Ghermo35** [comment]
-the app is great! In terms of on a mobile screen the pictures are very small to see. If possible just make them a bit bigger like they are on desktop and it’ll be great.  
- im on a iPhone 14 pro 
-

**Comment by asingh0725** [comment]
Thank you for pointing that out! We will fix the responsive styling of the feed page in phase 10.

**Comment by ryo884-2177391** [comment]
<img width="377" alt="Screenshot 2023-08-12 at 9 47 49 PM" src="https://github.com/info442-su23/i-team/assets/92127242/0bcb4f6a-45a4-435a-886c-76a4b905f76f">
Though the current UI seems to be responsive enough for the mobile, do we want to make them bigger?
