### ISSUE TITLE
Feature Request: Include some kind of indication that profile picture can be changed 

### ISSUE THREAD

**Issue by EloraHob** [info442-su23/i-team#74]
I clicked on the profile picture after logging in, assuming it would lead to a profile page or some kind of profile settings. Instead I was prompted to select an image to update my profile picture. 

I think some kind of on-hover effect to indicate that the user can upload a new photo by clicking might be more clear to the user.

**Comment by asingh0725** [comment]
We are going to implement this feature request in the next sprint. Here's how we plan to do it:
1) For first-time uploads, we will have a '+' sign as an indicator.
2) To update existing user images, we will have a hover-on effect indicating that users can upload a new photo.
